In [8]:
import numpy as np
import pandas as pd
# A structured array
my_array = np.ones(3, dtype=([('foo', int), ('bar', float)]))
print(my_array)
print(my_array['foo'])
print(my_array['bar'])

[(1,  1.) (1,  1.) (1,  1.)]
[1 1 1]
[ 1.  1.  1.]


In [9]:
# A record array
my_array2 = my_array.view(np.recarray)
print(my_array2.foo)
print(my_array2.bar)

[1 1 1]
[ 1.  1.  1.]


In [21]:
data = np.array([['','Col1','Col2'],
                ['Row1',1,2],
                ['Row2',3,4]])
print(data)

[['' 'Col1' 'Col2']
 ['Row1' '1' '2']
 ['Row2' '3' '4']]


In [22]:
print(pd.DataFrame(data=data[1:,1:],
                  index=data[1:,0],
                  columns=data[0,1:]))

     Col1 Col2
Row1    1    2
Row2    3    4


In [14]:
# Take a 2D array as input to your DataFrame 
my_2darray = np.array([[1, 2, 3], [4, 5, 6]])
print(pd.DataFrame(my_2darray))


   0  1  2
0  1  2  3
1  4  5  6


In [15]:
# Take a dictionary as input to your DataFrame 
my_dict = {1: ['1', '3'], 2: ['1', '2'], 3: ['2', '4']}
print(pd.DataFrame(my_dict))


   1  2  3
0  1  1  2
1  3  2  4


In [16]:
# Take a DataFrame as input to your DataFrame 
my_df = pd.DataFrame(data=[4,5,6,7], index=range(0,4), columns=['A'])
print(pd.DataFrame(my_df))


   A
0  4
1  5
2  6
3  7


In [17]:

# Take a Series as input to your DataFrame
my_series = pd.Series({"United Kingdom":"London", "India":"New Delhi", "United States":"Washington", "Belgium":"Brussels"})
print(pd.DataFrame(my_series))

                         0
Belgium           Brussels
India            New Delhi
United Kingdom      London
United States   Washington


In [24]:
df = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6]]))
print(df)

   0  1  2
0  1  2  3
1  4  5  6


In [20]:
# Use the `shape` property
print(df.shape)

(2, 3)


In [23]:
# Or use the `len()` function with the `index` property
print(len(df.index))

2


In [27]:
data = np.array([['','A','B','C'],
                ['0',1,2,3],
                ['1',4,5,6],
                ['2',7,8,9]])
print(data)

[['' 'A' 'B' 'C']
 ['0' '1' '2' '3']
 ['1' '4' '5' '6']
 ['2' '7' '8' '9']]


In [37]:
df = (pd.DataFrame(data=data[1:,1:],
                  index=data[1:,0],
                  columns=data[0,1:]))
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


In [47]:
# Using `iloc[]`
print(df.iloc[0][0])

# Using `loc[]`
#print(df.loc[0]['A'])

# Using `at[]`
#print(df.at[0,'A'])

# Using `iat[]`
print(df.iat[0,0])

1
1


In [48]:
# Use `iloc[]` to select a row
print(df.iloc[0])

# Use `loc[]` to select a column
print(df.loc[:,'A'])

A    1
B    2
C    3
Name: 0, dtype: object
0    1
1    4
2    7
Name: A, dtype: object
